version: "3.7"

services:
  backend:
    container_name: landingpage
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - VIRTUAL_HOST=nezha.guru
      - VIRTUAL_PORT=8090
      - LETSENCRYPT_HOST=nezha.guru
      - LETSENCRYPT_EMAIL=albertdavid0708@gmail.com

networks:
  default:
    name: nginx-proxy_default
